### ISSUE TITLE
Use the repository insteada of the map

### ISSUE THREAD

**Issue by matheusgr** [jvmafra/quem-me-ajuda#4]
https://github.com/jvmafra/quem-me-ajuda/blob/f394af80095bfddc8202ea6b923d091f10a106fb/src/main/java/qma/aluno/AlunoRepository.java#L20

A idéia do repositório e fazer o mapeamento de forma automática. Vale a pena ativar esse mapeamento aqui no lugar de definir um conjunto de métodos operando sobre uma coleção.

**Comment by jvmafra** [comment]
Feito. Fiz o mesmo para AjudaRepository
