### ISSUE TITLE
Colocar mais lógica de negócio aqui e menos no repositório

### ISSUE THREAD

**Issue by matheusgr** [jvmafra/quem-me-ajuda#5]
https://github.com/jvmafra/quem-me-ajuda/blob/f394af80095bfddc8202ea6b923d091f10a106fb/src/main/java/qma/aluno/AlunoServiceImpl.java#L18

Tenta deixar no repositório apenas as operações de CRUD e aqui ficar a responsabilidade de manipulações e adições.

**Comment by jvmafra** [comment]
Não tem mais nada no repositório. Tudo foi transferido para o service
